# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-04 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20200204_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('slug', 'language_code'), ('name', 'language_code')]),
        ),
    ]
