# Generated by Django 5.2.14 on 2026-05-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taggeditem",
            options={},
        ),
    ]
