# Generated by Django 5.0.6 on 2024-07-27 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="taggeditem",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
