[tox]
minversion = 1.9
envlist =
    black
    flake8
    isort
    py{310,311,312,313,314}-dj{52}
    py{310,311,312,313,314}-dj{60}
    py{310,311,312,313,314}-djmain
    docs

[gh-actions]
python =
    3.10: py310, black, flake8, isort
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    djmain: https://github.com/django/django/archive/main.tar.gz
    coverage
    djangorestframework
    unidecode
setenv =
    PYTHONWARNINGS=all
commands =
    coverage run -m django test --settings=tests.settings {posargs}
    coverage report
    coverage xml
ignore_outcome =
    djmain: True
ignore_errors =
    djmain: True

[testenv:black]
basepython = python3
skip_install = true
deps = black
commands = black --target-version=py310 --check --diff .

[testenv:flake8]
basepython = python3
skip_install = true
deps = flake8
commands = flake8

[testenv:isort]
basepython = python3
skip_install = true
deps = isort>=5.0.2
commands = isort --check-only --diff .

[testenv:docs]
deps = sphinx
commands = sphinx-build -n -W docs docs/_build
