# Generated by Django 4.2.30 on 2026-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0007_alter_multiinheritancelazyresolutionfoodtag_tag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taggedtrackedpet",
            options={
                "verbose_name": "tagged item",
                "verbose_name_plural": "tagged items",
            },
        ),
    ]
